### ISSUE TITLE
unable to deploy container

### ISSUE THREAD

**Issue by thejrose1984** [linuxserver/docker-openvpn-as#105]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Deploy container with persistent storage mounted to /config

## Current Behavior

Fails with this error spamming the log
`./run: line 3: /usr/local/openvpn_as/scripts/openvpnas: No such file or directory`

## Steps to Reproduce

1.deploy new stack or docker-compose with this: https://pastebin.com/R6e7rugD

## Environment
**OS:**      ubuntu 18.04
**CPU architecture:**       x86_64
**How docker service was installed:**      

sudo apt install docker.io

## Command used to create docker container (run/create/compose/screenshot)

https://pastebin.com/R6e7rugD
deployed via portainer swarm cluster

## Docker logs

https://pastebin.com/SvETgPnZ

**Comment by aptalca** [comment]
Most likely due to nfs config issues:
```
dpkg: error processing archive /openvpn/openvpn.deb (--install):,
 error setting ownership of '/usr/local/openvpn_as/sbin.dpkg-new': Operation not permitted,
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe),
```
Try the local filesystem

**Comment by thejrose1984** [comment]
It works without nfs share (I am able to spin up with non-persistent volumes). The question is how to resolve this. What ownership is it trying to change? The the sub-directory of the NFS share mounted as a volume is owned by the same UID/GID set in the environment section of the stack I provided.

**Comment by aptalca** [comment]
That's a question for openvpn-as as we are simply installing their package in that step.

In general, we don't recommend putting the `/config` folder of our apps on nfs (or any other remote) mounts because they cause various issues like the one you experienced.

**Comment by thejrose1984** [comment]
The core issue is that I am deploying to a six-node swarm cluster, so NFS is the solution used to make sure that persistent volumes don't break. If you have an alternate suggestion, I am open to discussion.

**Comment by aptalca** [comment]
I do not. That's one of the main reasons I'm not using swarm or k8s because the only remote mount option I could find that supports hosting database files (and mitigates other filesystem issues) is a paid enterprise plugin for k8s.

I read up a lot on k8s deployment with regards to either syncing local folders and/or using remote mounts for persistent data and was very disappointed to find no viable options. Most of the k8s guides out there either use docker images with stateless apps inside (node apps or basic nginx with static files in most cases), or if there is a mysql db involved, they use Google's Cloud SQL or another hosted sql option.

I'm sure k8s works great for apps that were designed to be run in a docker container, but openvpn-as was not, and part of the process of dockerizing it without losing data throughout image updates and container recreation involves installing the package on a `/config` mounted location.

**Comment by thejrose1984** [comment]
perhaps, but this is the only linuxserver.io container that I've had issues with (thus far) where using nfs was an issue. if the whole point of persistent volumes is to avoid losing *data*, then why are we trying to install a package there via dpkg? perhaps the location of the symlink needs to be re-evaluated?

**Comment by aptalca** [comment]
Because we are trying to shoehorn an application that is not designed to be run in docker into a docker image.

Openvpn-as is not even opensource, they only release ubuntu/debian packages with their binaries in them, and are designed to run on an ubuntu desktop system.

Try installing version 2.7.9 on bare metal ubuntu, copy the data elsewhere, upgrade to 2.8.0, copy the data back over and watch it fail. Openvpn-as only allows in place updates and backup/restore with their tools. It's a PITA. That's why we resort to installing it in the config folder so we can perform in place updates and not break the whole thing with every version update.

**Comment by thejrose1984** [comment]
okay - thanks for the clarification
