### ISSUE TITLE
Error in documentation on Docker website

### ISSUE THREAD

**Issue by coyotanark** [linuxserver/docker-openvpn-as#82]
https://hub.docker.com/r/linuxserver/openvpn-as

refers to this command to install:
docker create \
  --name=openvpn-as \
  --cap-add=NET_ADMIN \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e INTERFACE=eth0 `#optional` \
  -p 943:943 \
  -p 9443:9443 \
  -p 1194:1194/udp \
  -v path to data:/config \
  --restart unless-stopped \
  linuxserver/openvpn-as

But per https://docs.docker.com/engine/reference/commandline/create/

docker create [OPTIONS] IMAGE [COMMAND] [ARG...]
While here the image is at the end causing: 

Unable to find image 'to:latest' locally
Error response from daemon: pull access denied for to, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

A fixed version (inline) is:
docker create --name=openvpn-as --cap-add=NET_ADMIN linuxserver/openvpn-as -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -p 943:943 -p 9443:9443 -p 1194:1194/udp -v path to data:/config --restart unless-stopped 

Thanks guys

**Comment by j0nnymoe** [comment]
No you received that error due to not replacing `path to data` to your own folder.

**Comment by coyotanark** [comment]
Hi

can you please elaborate what should be replaced? Nothing is mentioned about this on the setup tutorial

**Comment by aptalca** [comment]
Dockerbhub removes some formatting. On GitHub readme where this is synced from, it reads `-v <path to data>:/config`. You're supposed to replace `<path to data>` with a path of your choice on the host where all the config files will be stored and will be persistent.

We don't further explain that because we assume that the users have some basic understanding of docker concepts like folder mapping.
